---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[smrtlink::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      smrtlink:
        service:
          reload: true
        paths:
          SMRT_ROOT: /opt/smrtlink
        local_dirs:
          /opt/smrtlink:
            target: /var/tmp/smrtlink
            link: true
          /opt/smrtlink/db_datadir:
            target: /var/tmp/db_datadir
            link: false
